"""initial schema

Revision ID: 20260107_1733_381db1c8de34
Revises:
Create Date: 2026-01-07 17:33:00.008412+01:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260107_1733_381db1c8de34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditor_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_name_normalized', sa.String(length=255), nullable=True),
    sa.Column('creditor_name', sa.String(length=255), nullable=False),
    sa.Column('creditor_email', sa.String(length=255), nullable=False),
    sa.Column('creditor_name_normalized', sa.String(length=255), nullable=True),
    sa.Column('debt_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('zendesk_ticket_id', sa.String(length=50), nullable=False),
    sa.Column('zendesk_side_conversation_id', sa.String(length=50), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditor_inquiries_client_name'), 'creditor_inquiries', ['client_name'], unique=False)
    op.create_index(op.f('ix_creditor_inquiries_client_name_normalized'), 'creditor_inquiries', ['client_name_normalized'], unique=False)
    op.create_index(op.f('ix_creditor_inquiries_creditor_email'), 'creditor_inquiries', ['creditor_email'], unique=False)
    op.create_index(op.f('ix_creditor_inquiries_creditor_name'), 'creditor_inquiries', ['creditor_name'], unique=False)
    op.create_index(op.f('ix_creditor_inquiries_creditor_name_normalized'), 'creditor_inquiries', ['creditor_name_normalized'], unique=False)
    op.create_index(op.f('ix_creditor_inquiries_id'), 'creditor_inquiries', ['id'], unique=False)
    op.create_index(op.f('ix_creditor_inquiries_reference_number'), 'creditor_inquiries', ['reference_number'], unique=False)
    op.create_index(op.f('ix_creditor_inquiries_zendesk_side_conversation_id'), 'creditor_inquiries', ['zendesk_side_conversation_id'], unique=False)
    op.create_index(op.f('ix_creditor_inquiries_zendesk_ticket_id'), 'creditor_inquiries', ['zendesk_ticket_id'], unique=False)
    op.create_table('incoming_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zendesk_ticket_id', sa.String(length=50), nullable=False),
    sa.Column('zendesk_webhook_id', sa.String(length=100), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('raw_body_html', sa.Text(), nullable=True),
    sa.Column('raw_body_text', sa.Text(), nullable=True),
    sa.Column('cleaned_body', sa.Text(), nullable=True),
    sa.Column('token_count_before', sa.Integer(), nullable=True),
    sa.Column('token_count_after', sa.Integer(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('matched_inquiry_id', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.String(length=50), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zendesk_webhook_id')
    )
    op.create_index(op.f('ix_incoming_emails_from_email'), 'incoming_emails', ['from_email'], unique=False)
    op.create_index(op.f('ix_incoming_emails_id'), 'incoming_emails', ['id'], unique=False)
    op.create_index(op.f('ix_incoming_emails_matched_inquiry_id'), 'incoming_emails', ['matched_inquiry_id'], unique=False)
    op.create_index(op.f('ix_incoming_emails_zendesk_ticket_id'), 'incoming_emails', ['zendesk_ticket_id'], unique=False)
    # match_results table created in later migration (20260205_1923_add_matching)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # match_results dropped in migration 20260205_1923_add_matching
    op.drop_index(op.f('ix_incoming_emails_zendesk_ticket_id'), table_name='incoming_emails')
    op.drop_index(op.f('ix_incoming_emails_matched_inquiry_id'), table_name='incoming_emails')
    op.drop_index(op.f('ix_incoming_emails_id'), table_name='incoming_emails')
    op.drop_index(op.f('ix_incoming_emails_from_email'), table_name='incoming_emails')
    op.drop_table('incoming_emails')
    op.drop_index(op.f('ix_creditor_inquiries_zendesk_ticket_id'), table_name='creditor_inquiries')
    op.drop_index(op.f('ix_creditor_inquiries_zendesk_side_conversation_id'), table_name='creditor_inquiries')
    op.drop_index(op.f('ix_creditor_inquiries_reference_number'), table_name='creditor_inquiries')
    op.drop_index(op.f('ix_creditor_inquiries_id'), table_name='creditor_inquiries')
    op.drop_index(op.f('ix_creditor_inquiries_creditor_name_normalized'), table_name='creditor_inquiries')
    op.drop_index(op.f('ix_creditor_inquiries_creditor_name'), table_name='creditor_inquiries')
    op.drop_index(op.f('ix_creditor_inquiries_creditor_email'), table_name='creditor_inquiries')
    op.drop_index(op.f('ix_creditor_inquiries_client_name_normalized'), table_name='creditor_inquiries')
    op.drop_index(op.f('ix_creditor_inquiries_client_name'), table_name='creditor_inquiries')
    op.drop_table('creditor_inquiries')
    # ### end Alembic commands ###
